import json

file = open("mapa-virtual.json")
bd = json.load(file)
file.close()

ttl = """@prefix : <http://rpcw.di.uminho.pt/2024/mapa-virtual/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/mapa-virtual/> .

<http://rpcw.di.uminho.pt/2024/mapa-virtual> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#destino
:destino rdf:type owl:ObjectProperty ;
         rdfs:domain :Ligacao ;
         rdfs:range :Cidade .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#origem
:origem rdf:type owl:ObjectProperty ;
        rdfs:domain :Ligacao ;
        rdfs:range :Cidade .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#descricao
:descricao rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#distancia
:distancia rdf:type owl:DatatypeProperty ;
           rdfs:domain :Ligacao ;
           rdfs:range xsd:float .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#distrito
:distrito rdf:type owl:DatatypeProperty ;
          rdfs:domain :Cidade ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#nome
:nome rdf:type owl:DatatypeProperty ;
      rdfs:domain :Cidade ;
      rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#populacao
:populacao rdf:type owl:DatatypeProperty ;
           rdfs:domain :Cidade ;
           rdfs:range xsd:int .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/mapa-virtual#Cidade
:Cidade rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/mapa-virtual#Ligacao
:Ligacao rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################

"""

for cidade in bd["cidades"]:
    ttl += f"""###  http://rpcw.di.uminho.pt/2024/mapa-virtual#{cidade['id']}
:{cidade['id']} rdf:type owl:NamedIndividual ,
              :Cidade ;
     :descricao "{cidade['descrição']}" ;
     :distrito "{cidade['distrito']}" ;
     :nome "{cidade['nome']}" ;
     :populacao "{cidade['população']}"^^xsd:int .

       
"""
    
for ligacao in bd["ligacoes"]:
    ttl += f"""###  http://rpcw.di.uminho.pt/2024/mapa-virtual#{ligacao['id']}
:{ligacao['id']} rdf:type owl:NamedIndividual ,
                :Ligacao ;
       :destino :{ligacao['destino']} ;
       :origem :{ligacao['origem']} ;
       :distancia "{ligacao['distância']}"^^xsd:float .

     
"""

ttl += "###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi"

print(ttl)