import json

file = open("escolaMusica.json")
bd = json.load(file)
file.close()

ttl = """@prefix : <http://rpcw.di.uminho.pt/2024/escolaMusica/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://rpcw.di.uminho.pt/2024/escolaMusica/> .

<http://rpcw.di.uminho.pt/2024/escolaMusica> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/escolaMusica#frequentaCurso
:frequentaCurso rdf:type owl:ObjectProperty ;
                rdfs:domain :Aluno ;
                rdfs:range :Curso .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#temInstrumento
:temInstrumento rdf:type owl:ObjectProperty ;
                rdfs:domain :Curso ;
                rdfs:range :Instrumento .


#################################################################
#    Data properties
#################################################################

###  http://rpcw.di.uminho.pt/2024/escolaMusica#anoCurso
:anoCurso rdf:type owl:DatatypeProperty ;
          rdfs:domain :Aluno ;
          rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#dataNasc
:dataNasc rdf:type owl:DatatypeProperty ;
          rdfs:domain :Aluno ;
          rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#designacao
:designacao rdf:type owl:DatatypeProperty ;
            rdfs:domain :Curso ;
            rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#duracao
:duracao rdf:type owl:DatatypeProperty ;
         rdfs:domain :Curso ;
         rdfs:range xsd:int .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#nomeAluno
:nomeAluno rdf:type owl:DatatypeProperty ;
           rdfs:domain :Aluno ;
           rdfs:range xsd:string .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#nomeInstrumento
:nomeInstrumento rdf:type owl:DatatypeProperty ;
                 rdfs:domain :Instrumento ;
                 rdfs:range xsd:string .


#################################################################
#    Classes
#################################################################

###  http://rpcw.di.uminho.pt/2024/escolaMusica#Aluno
:Aluno rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#Curso
:Curso rdf:type owl:Class .


###  http://rpcw.di.uminho.pt/2024/escolaMusica#Instrumento
:Instrumento rdf:type owl:Class .


#################################################################
#    Individuals
#################################################################

"""

for aluno in bd["alunos"]:
    ttl += f"""###  http://rpcw.di.uminho.pt/2024/escolaMusica#{aluno["id"]}
:{aluno["id"]} rdf:type owl:NamedIndividual ,
                :Aluno ;
       :frequentaCurso :{aluno["curso"]} ;
       :anoCurso "{aluno["anoCurso"]}"^^xsd:int ;
       :dataNasc "{aluno["dataNasc"]}" ;
       :nomeAluno "{aluno["nome"]}" .

       
"""
    
for curso in bd["cursos"]:
    ttl += f"""###  http://rpcw.di.uminho.pt/2024/escolaMusica#{curso["id"]}
:{curso["id"]} rdf:type owl:NamedIndividual ,
              :Curso ;
     :temInstrumento :{curso["instrumento"]["id"]} ;
     :designacao "{curso["designacao"]}" ;
     :duracao "{curso["duracao"]}"^^xsd:int .

     
"""
    
for instrumento in bd["instrumentos"]:
    ttl += f"""###  http://rpcw.di.uminho.pt/2024/escolaMusica#{instrumento["id"]}
:{instrumento["id"]} rdf:type owl:NamedIndividual ,
             :Instrumento ;
    :nomeInstrumento "{instrumento["#text"]}" .

    
"""

ttl += "###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi"

print(ttl)
